version: "3"
services:
  nginx:
    image: nginx:1.14
    depends_on:
      - php-fpm
    links:
      - php-fpm
    env_file:
      - ./.env
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ./docker/nginx/:/etc/nginx/conf.d/
      - .:/var/www/project

  database:
    image: postgres:13
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER:${POSTGRES_USER}
      - POSTGRES_PASSWORD:${POSTGRES_PASSWORD}
      - POSTGRES_DB:${POSTGRES_DB}
    ports:
      - ${PG_EXT_PORT}:5432
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data

  php-fpm:
    build: docker/php
    depends_on:
      - database
    links:
      - database
    volumes:
      - .:/var/www/project
    working_dir: /var/www/project
    env_file:
      - ./.env

volumes:
  data: { }
